apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-kafka-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-kafka-app
  template:
    metadata:
      labels:
        app: spring-kafka-app
    spec:
      containers:
        - name: spring-kafka-app
          image: localhost:5001/spring-kafka-app:1.0.2   # 👈 pull from your local registry
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-broker-service:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: spring-kafka-service
spec:
  selector:
    app: spring-kafka-app
  ports:
    - port: 8080        # exposed port
      targetPort: 8081  # container port
      nodePort: 30081   # fixed host port
  type: NodePort
